export const designation = [
    { value: "sde1", label: "SDE I" },
    { value: "sde2", label: "SDE II" },
    { value: "senior-sde", label: "Sr. SDE" },
    { value: "lead-sde", label: "Lead SDE" },
    { value: "architect", label: "Architect" },
    { value: "pm", label: "PM" },
    { value: "qa", label: "QA" },
    { value: "devops", label: "DevOps" },
    { value: "ux-designer", label: "UX Designer" },
    { value: "ui-designer", label: "UI Designer" },
    { value: "fullstack-dev", label: "Full-Stack Dev" },
    { value: "frontend-dev", label: "Frontend Dev" },
    { value: "backend-dev", label: "Backend Dev" },
    { value: "data-scientist", label: "Data Scientist" },
    { value: "data-analyst", label: "Data Analyst" },
    { value: "sys-admin", label: "Sys Admin" },
    { value: "network-engineer", label: "Network Eng." },
    { value: "security-engineer", label: "Sec. Engineer" },
    { value: "technical-writer", label: "Tech Writer" },
    { value: "product-owner", label: "Product Owner" },
    { value: "scrum-master", label: "Scrum Master" },
    { value: "intern", label: "Intern" },                    
    { value: "undergrad", label: "Undergraduate" },      
    { value: "grad", label: "Graduate" },                      
    { value: "research-assistant", label: "Research Asst." }, 
    { value: "teaching-assistant", label: "Teaching Asst." },     
    { value: "volunteer", label: "Volunteer" },               
    { value: "co-op", label: "Co-op Student" },             
    { value: "exchange-student", label: "Exchange Student" }, 
    { value: "fellow", label: "Fellow" },  
    { value: "student", label: "Student" },                    
  ];